import requests
import os

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
REPO = "tanvi120/pyci-guardian"


def create_pull_request(branch_name):
    url = f"https://api.github.com/repos/{REPO}/pulls"

    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github+json"
    }

    data = {
        "title": "Auto Fix by PyCI Guardian",
        "head": branch_name,
        "base": "main",
        "body": "This PR was automatically generated by PyCI Guardian."
    }

    response = requests.post(url, json=data, headers=headers)

    if response.status_code == 201:
        print("🚀 PR created successfully!")
        print(response.json()["html_url"])
    else:
        print("❌ Failed to create PR:", response.text)
